site_name: 学无止境
site_description: 学无止境 Documentation
site_author: Stephen Ho
repo_url: https://github.com/heweijian4933/learn
repo_name: learn
edit_uri: edit/master/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  font:
    text: Noto Sans SC
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: 
        - zh
        - en
  - tags
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heweijian4933
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 cookies 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
    actions:
      - accept
      - reject
      - manage

nav:
  - 首页: index.md
  - 后端开发:
    - backend/index.md
    - Java: backend/java/
    - MySQL:
      - MySQL实战45讲:
        - 开篇词: backend/mysql/MySQL实战45讲/开篇词-这一次，让我们一起来搞懂MySQL.md
        - 基础篇:
          - 基础架构：一条SQL查询语句是如何执行的？: backend/mysql/MySQL实战45讲/01-基础架构：一条SQL查询语句是如何执行的？.md
          - 日志系统：一条SQL更新语句是如何执行的？: backend/mysql/MySQL实战45讲/02-日志系统：一条SQL更新语句是如何执行的？.md
          - 事务隔离：为什么你改了我还看不见？: backend/mysql/MySQL实战45讲/03-事务隔离：为什么你改了我还看不见？.md
        - 索引篇:
          - 深入浅出索引（上）: backend/mysql/MySQL实战45讲/04-深入浅出索引（上）.md
          - 深入浅出索引（下）: backend/mysql/MySQL实战45讲/05-深入浅出索引（下）.md
        - 锁篇:
          - 全局锁和表锁：给表加个字段怎么有这么多阻碍？: backend/mysql/MySQL实战45讲/06-全局锁和表锁：给表加个字段怎么有这么多阻碍？.md
          - 行锁功过：怎么减少行锁对性能的影响？: backend/mysql/MySQL实战45讲/07-行锁功过：怎么减少行锁对性能的影响？.md
          - 事务到底是隔离的还是不隔离的？: backend/mysql/MySQL实战45讲/08-事务到底是隔离的还是不隔离的？.md
        - 实战篇:
          - 普通索引和唯一索引，应该怎么选择？: backend/mysql/MySQL实战45讲/09-普通索引和唯一索引，应该怎么选择？.md
          - MySQL为什么有时候会选错索引？: backend/mysql/MySQL实战45讲/10-MySQL为什么有时候会选错索引？.md
          - 怎么给字符串字段加索引？: backend/mysql/MySQL实战45讲/11-怎么给字符串字段加索引？.md
          - 为什么我的MySQL会"抖"一下？: backend/mysql/MySQL实战45讲/12-为什么我的MySQL会"抖"一下？.md
          - 为什么表数据删掉一半，表文件大小不变？: backend/mysql/MySQL实战45讲/13-为什么表数据删掉一半，表文件大小不变？.md
          - count(*)这么慢，我该怎么办？: backend/mysql/MySQL实战45讲/14-count(-)这么慢，我该怎么办？.md
        - 进阶优化篇:
          - 答疑文章（一）：日志和索引相关问题: backend/mysql/MySQL实战45讲/15-答疑文章（一）：日志和索引相关问题.md
          - '"order by"是怎么工作的?': 'backend/mysql/MySQL实战45讲/16-"orderby"是怎么工作的？.md'
          - 如何正确地显示随机消息？: backend/mysql/MySQL实战45讲/17-如何正确地显示随机消息？.md
          - 为什么这些SQL语句逻辑相同，性能却差异巨大？: backend/mysql/MySQL实战45讲/18-为什么这些SQL语句逻辑相同，性能却差异巨大？.md
          - 为什么我只查一行的语句，也执行这么慢？: backend/mysql/MySQL实战45讲/19-为什么我只查一行的语句，也执行这么慢？.md
        - 事务与锁进阶篇:
          - 幻读是什么，幻读有什么问题？: backend/mysql/MySQL实战45讲/20-幻读是什么，幻读有什么问题？.md
          - 为什么我只改一行的语句，锁这么多？: backend/mysql/MySQL实战45讲/21-为什么我只改一行的语句，锁这么多？.md
          - MySQL有哪些"饮鸩止渴"提高性能的方法？: backend/mysql/MySQL实战45讲/22-MySQL有哪些"饮鸩止渴"提高性能的方法？.md
        - 高可用篇:
          - MySQL是怎么保证数据不丢的？: backend/mysql/MySQL实战45讲/23-MySQL是怎么保证数据不丢的？.md
          - MySQL是怎么保证主备一致的？: backend/mysql/MySQL实战45讲/24-MySQL是怎么保证主备一致的？.md
          - MySQL是怎么保证高可用的？: backend/mysql/MySQL实战45讲/25-MySQL是怎么保证高可用的？.md
          - 备库为什么会延迟好几个小时？: backend/mysql/MySQL实战45讲/26-备库为什么会延迟好几个小时？.md
          - 主库出问题了，从库怎么办？: backend/mysql/MySQL实战45讲/27-主库出问题了，从库怎么办？.md
          - 读写分离有哪些坑？: backend/mysql/MySQL实战45讲/28-读写分离有哪些坑？.md
        - 系统运维篇:
          - 如何判断一个数据库是不是出问题了？: backend/mysql/MySQL实战45讲/29-如何判断一个数据库是不是出问题了？.md
          - 答疑文章（二）：用动态的观点看加锁: backend/mysql/MySQL实战45讲/30-答疑文章（二）：用动态的观点看加锁.md
          - 误删数据后除了跑路，还能怎么办？: backend/mysql/MySQL实战45讲/31-误删数据后除了跑路，还能怎么办？.md
          - 为什么还有kill不掉的语句？: backend/mysql/MySQL实战45讲/32-为什么还有kill不掉的语句？.md
          - 我查这么多数据，会不会把数据库内存打爆？: backend/mysql/MySQL实战45讲/33-我查这么多数据，会不会把数据库内存打爆？.md
        - SQL优化篇:
          - 到底可不可以使用join？: backend/mysql/MySQL实战45讲/34-到底可不可以使用join？.md
          - join语句怎么优化？: backend/mysql/MySQL实战45讲/35-join语句怎么优化？.md
          - 为什么临时表可以重名？: backend/mysql/MySQL实战45讲/36-为什么临时表可以重名？.md
          - 什么时候会使用内部临时表？: backend/mysql/MySQL实战45讲/37-什么时候会使用内部临时表？.md
        - 引擎与存储篇:
          - 都说InnoDB好，那还要不要使用Memory引擎？: backend/mysql/MySQL实战45讲/38-都说InnoDB好，那还要不要使用Memory引擎？.md
          - 自增主键为什么不是连续的？: backend/mysql/MySQL实战45讲/39-自增主键为什么不是连续的？.md
          - insert语句的锁为什么这么多？: backend/mysql/MySQL实战45讲/40-insert语句的锁为什么这么多？.md
          - 怎么最快地复制一张表？: backend/mysql/MySQL实战45讲/41-怎么最快地复制一张表？.md
        - 答疑与总结篇:
          - grant之后要跟着flush privileges吗？: backend/mysql/MySQL实战45讲/42-grant之后要跟着flushprivileges吗？.md
          - 要不要使用分区表？: backend/mysql/MySQL实战45讲/43-要不要使用分区表？.md
          - 答疑文章（三）：说一说这些好问题: backend/mysql/MySQL实战45讲/44-答疑文章（三）：说一说这些好问题.md
          - 自增id用完怎么办？: backend/mysql/MySQL实战45讲/45-自增id用完怎么办？.md
        - 结语:
          - 直播回顾：林晓斌：我的MySQL心路历程: backend/mysql/MySQL实战45讲/直播回顾-林晓斌：我的MySQL心路历程.md
          - 结课测试：这些MySQL知识你都掌握了吗？: backend/mysql/MySQL实战45讲/结课测试｜这些MySQL知识你都掌握了吗？.md
          - 结束语：点线网面，一起构建MySQL知识网络: backend/mysql/MySQL实战45讲/结束语-点线网面，一起构建MySQL知识网络.md
  - 前端开发:
    - frontend/index.md