site_name: 学无止境
site_description: 学无止境 Documentation
site_author: Stephen Ho
repo_url: https://github.com/heweijian4933/learn
repo_name: learn
edit_uri: edit/master/docs/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - toc.follow
    - search.highlight
    - search.share
    - search.suggest
    - content.code.copy
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  font:
    text: Noto Sans SC
    code: Roboto Mono
  icon:
    repo: fontawesome/brands/github

plugins:
  - search:
      lang: 
        - zh
        - en
  - tags
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
  - git-authors

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - tables
  - footnotes
  - toc:
      permalink: true
      toc_depth: 4

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/heweijian4933
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  consent:
    title: Cookie 同意
    description: >- 
      我们使用 cookies 来识别您的重复访问和偏好，以及衡量我们文档的有效性和用户是否找到他们要找的内容。
    cookies:
      analytics: Google Analytics
    actions:
      - accept
      - reject
      - manage

nav:
  - 首页: index.md
  - 后端开发:
    - backend/index.md
    - Java: backend/java/
  - 前端开发:
    - frontend/index.md